System.config({
    "babelOptions": {
        "optional": [
            "runtime",
            "optimisation.modules.system"
        ]
    },
    "baseURL": "js/",
    "bundles": {
        "app.js": [
            "actions/TicketsActions.js",
            "actions/corporate_cards/manufacturing_facilities.js",
            "actions/corporate_cards/medical_center.js",
            "actions/corporate_cards/testing.js",
            "actions/transport/LogActions.js",
            "components/common/card_select.js",
            "components/common/card_select/card.js",
            "components/common/card_select/cards.js",
            "components/common/card_select/ddcontext.js",
            "components/common/card_select/dzone.js",
            "components/common/card_select_dialog.js",
            "components/common/order_success_dialog.js",
            "components/common/pinpad.js",
            "components/common/widget-selector.js",
            "components/corporate_cards/cafeteria.js",
            "components/corporate_cards/cafeteria_buyer_check.js",
            "components/corporate_cards/cafeteria_menu.js",
            "components/corporate_cards/human_resources_department.js",
            "components/corporate_cards/index.js",
            "components/corporate_cards/manufacturing_facilities.js",
            "components/corporate_cards/manufacturing_facilities_access.js",
            "components/corporate_cards/manufacturing_facilities_access_denied.js",
            "components/corporate_cards/manufacturing_facilities_access_granted.js",
            "components/corporate_cards/manufacturing_facilities_inventory.js",
            "components/corporate_cards/manufacturing_facilities_inventory_issued.js",
            "components/corporate_cards/manufacturing_facilities_monitor.js",
            "components/corporate_cards/manufacturing_facilities_monitor_access.js",
            "components/corporate_cards/manufacturing_facilities_services.js",
            "components/corporate_cards/medical_center.js",
            "components/corporate_cards/medical_center_results.js",
            "components/corporate_cards/office.js",
            "components/corporate_cards/office_auth.js",
            "components/corporate_cards/office_report_sign.js",
            "components/corporate_cards/office_workspace.js",
            "components/corporate_cards/professional_qualification_testing.js",
            "components/corporate_cards/safety_testing.js",
            "components/corporate_cards/select_corporate_card.js",
            "components/corporate_cards/services.js",
            "components/corporate_cards/task_table.js",
            "components/corporate_cards/testing/answer.js",
            "components/corporate_cards/testing/question.js",
            "components/corporate_cards/testing/testing.js",
            "components/corporate_cards/testing_results.js",
            "components/gov-services/auth-by-card.js",
            "components/gov-services/index.js",
            "components/gov-services/lk.js",
            "components/gov-services/operator-arm.js",
            "components/gov-services/regional-services.js",
            "components/gov-services/services.js",
            "components/home.js",
            "components/loyalty/index.js",
            "components/loyalty/loyalty-arm.js",
            "components/loyalty/loyalty-market.js",
            "components/loyalty/market/bucket.js",
            "components/loyalty/services.js",
            "components/not_found.js",
            "components/social_tickets/index.js",
            "components/social_tickets/order.js",
            "components/social_tickets/order/events.js",
            "components/social_tickets/order/places.js",
            "components/social_tickets/services.js",
            "components/social_tickets/terminal.js",
            "components/transport/index.js",
            "components/transport/services.js",
            "components/transport/supervisor_terminal.js",
            "components/transport/terminal.js",
            "components/transport/terminal/card.js",
            "components/transport/terminal/order.js",
            "components/transport/validator.js",
            "components/utilities/scrollbar.js",
            "constants/ActionTypes.js",
            "constants/ItemTypes.js",
            "containers/body.js",
            "containers/layout.js",
            "containers/presentation_page.js",
            "github:jspm/nodelibs-process@0.1.2.js",
            "github:jspm/nodelibs-process@0.1.2/index.js",
            "main.js",
            "npm:asap@2.0.5.js",
            "npm:asap@2.0.5/asap.js",
            "npm:asap@2.0.5/browser-raw.js",
            "npm:babel-runtime@5.8.38/core-js/array/from.js",
            "npm:babel-runtime@5.8.38/core-js/get-iterator.js",
            "npm:babel-runtime@5.8.38/core-js/is-iterable.js",
            "npm:babel-runtime@5.8.38/core-js/number/is-finite.js",
            "npm:babel-runtime@5.8.38/core-js/number/is-integer.js",
            "npm:babel-runtime@5.8.38/core-js/object/assign.js",
            "npm:babel-runtime@5.8.38/core-js/object/create.js",
            "npm:babel-runtime@5.8.38/core-js/object/define-properties.js",
            "npm:babel-runtime@5.8.38/core-js/object/define-property.js",
            "npm:babel-runtime@5.8.38/core-js/object/freeze.js",
            "npm:babel-runtime@5.8.38/core-js/object/get-own-property-descriptor.js",
            "npm:babel-runtime@5.8.38/core-js/object/keys.js",
            "npm:babel-runtime@5.8.38/core-js/object/set-prototype-of.js",
            "npm:babel-runtime@5.8.38/helpers/class-call-check.js",
            "npm:babel-runtime@5.8.38/helpers/create-class.js",
            "npm:babel-runtime@5.8.38/helpers/define-property.js",
            "npm:babel-runtime@5.8.38/helpers/extends.js",
            "npm:babel-runtime@5.8.38/helpers/get.js",
            "npm:babel-runtime@5.8.38/helpers/inherits.js",
            "npm:babel-runtime@5.8.38/helpers/object-without-properties.js",
            "npm:babel-runtime@5.8.38/helpers/sliced-to-array.js",
            "npm:babel-runtime@5.8.38/helpers/tagged-template-literal.js",
            "npm:babel-runtime@5.8.38/helpers/to-consumable-array.js",
            "npm:classnames@2.2.5.js",
            "npm:classnames@2.2.5/index.js",
            "npm:core-js@1.2.7/library/fn/array/from.js",
            "npm:core-js@1.2.7/library/fn/get-iterator.js",
            "npm:core-js@1.2.7/library/fn/is-iterable.js",
            "npm:core-js@1.2.7/library/fn/number/is-finite.js",
            "npm:core-js@1.2.7/library/fn/number/is-integer.js",
            "npm:core-js@1.2.7/library/fn/object/assign.js",
            "npm:core-js@1.2.7/library/fn/object/create.js",
            "npm:core-js@1.2.7/library/fn/object/define-properties.js",
            "npm:core-js@1.2.7/library/fn/object/define-property.js",
            "npm:core-js@1.2.7/library/fn/object/freeze.js",
            "npm:core-js@1.2.7/library/fn/object/get-own-property-descriptor.js",
            "npm:core-js@1.2.7/library/fn/object/keys.js",
            "npm:core-js@1.2.7/library/fn/object/set-prototype-of.js",
            "npm:core-js@1.2.7/library/modules/$.a-function.js",
            "npm:core-js@1.2.7/library/modules/$.add-to-unscopables.js",
            "npm:core-js@1.2.7/library/modules/$.an-object.js",
            "npm:core-js@1.2.7/library/modules/$.classof.js",
            "npm:core-js@1.2.7/library/modules/$.cof.js",
            "npm:core-js@1.2.7/library/modules/$.core.js",
            "npm:core-js@1.2.7/library/modules/$.ctx.js",
            "npm:core-js@1.2.7/library/modules/$.defined.js",
            "npm:core-js@1.2.7/library/modules/$.descriptors.js",
            "npm:core-js@1.2.7/library/modules/$.export.js",
            "npm:core-js@1.2.7/library/modules/$.fails.js",
            "npm:core-js@1.2.7/library/modules/$.global.js",
            "npm:core-js@1.2.7/library/modules/$.has.js",
            "npm:core-js@1.2.7/library/modules/$.hide.js",
            "npm:core-js@1.2.7/library/modules/$.iobject.js",
            "npm:core-js@1.2.7/library/modules/$.is-array-iter.js",
            "npm:core-js@1.2.7/library/modules/$.is-integer.js",
            "npm:core-js@1.2.7/library/modules/$.is-object.js",
            "npm:core-js@1.2.7/library/modules/$.iter-call.js",
            "npm:core-js@1.2.7/library/modules/$.iter-create.js",
            "npm:core-js@1.2.7/library/modules/$.iter-define.js",
            "npm:core-js@1.2.7/library/modules/$.iter-detect.js",
            "npm:core-js@1.2.7/library/modules/$.iter-step.js",
            "npm:core-js@1.2.7/library/modules/$.iterators.js",
            "npm:core-js@1.2.7/library/modules/$.js",
            "npm:core-js@1.2.7/library/modules/$.library.js",
            "npm:core-js@1.2.7/library/modules/$.object-assign.js",
            "npm:core-js@1.2.7/library/modules/$.object-sap.js",
            "npm:core-js@1.2.7/library/modules/$.property-desc.js",
            "npm:core-js@1.2.7/library/modules/$.redefine.js",
            "npm:core-js@1.2.7/library/modules/$.set-proto.js",
            "npm:core-js@1.2.7/library/modules/$.set-to-string-tag.js",
            "npm:core-js@1.2.7/library/modules/$.shared.js",
            "npm:core-js@1.2.7/library/modules/$.string-at.js",
            "npm:core-js@1.2.7/library/modules/$.to-integer.js",
            "npm:core-js@1.2.7/library/modules/$.to-iobject.js",
            "npm:core-js@1.2.7/library/modules/$.to-length.js",
            "npm:core-js@1.2.7/library/modules/$.to-object.js",
            "npm:core-js@1.2.7/library/modules/$.uid.js",
            "npm:core-js@1.2.7/library/modules/$.wks.js",
            "npm:core-js@1.2.7/library/modules/core.get-iterator-method.js",
            "npm:core-js@1.2.7/library/modules/core.get-iterator.js",
            "npm:core-js@1.2.7/library/modules/core.is-iterable.js",
            "npm:core-js@1.2.7/library/modules/es6.array.from.js",
            "npm:core-js@1.2.7/library/modules/es6.array.iterator.js",
            "npm:core-js@1.2.7/library/modules/es6.number.is-finite.js",
            "npm:core-js@1.2.7/library/modules/es6.number.is-integer.js",
            "npm:core-js@1.2.7/library/modules/es6.object.assign.js",
            "npm:core-js@1.2.7/library/modules/es6.object.freeze.js",
            "npm:core-js@1.2.7/library/modules/es6.object.get-own-property-descriptor.js",
            "npm:core-js@1.2.7/library/modules/es6.object.keys.js",
            "npm:core-js@1.2.7/library/modules/es6.object.set-prototype-of.js",
            "npm:core-js@1.2.7/library/modules/es6.string.iterator.js",
            "npm:core-js@1.2.7/library/modules/web.dom.iterable.js",
            "npm:disposables@1.0.1.js",
            "npm:disposables@1.0.1/modules/CompositeDisposable.js",
            "npm:disposables@1.0.1/modules/Disposable.js",
            "npm:disposables@1.0.1/modules/SerialDisposable.js",
            "npm:disposables@1.0.1/modules/index.js",
            "npm:disposables@1.0.1/modules/isDisposable.js",
            "npm:dnd-core@2.2.3.js",
            "npm:dnd-core@2.2.3/lib/DragDropManager.js",
            "npm:dnd-core@2.2.3/lib/DragDropMonitor.js",
            "npm:dnd-core@2.2.3/lib/DragSource.js",
            "npm:dnd-core@2.2.3/lib/DropTarget.js",
            "npm:dnd-core@2.2.3/lib/HandlerRegistry.js",
            "npm:dnd-core@2.2.3/lib/actions/dragDrop.js",
            "npm:dnd-core@2.2.3/lib/actions/registry.js",
            "npm:dnd-core@2.2.3/lib/backends/createTestBackend.js",
            "npm:dnd-core@2.2.3/lib/index.js",
            "npm:dnd-core@2.2.3/lib/reducers/dirtyHandlerIds.js",
            "npm:dnd-core@2.2.3/lib/reducers/dragOffset.js",
            "npm:dnd-core@2.2.3/lib/reducers/dragOperation.js",
            "npm:dnd-core@2.2.3/lib/reducers/index.js",
            "npm:dnd-core@2.2.3/lib/reducers/refCount.js",
            "npm:dnd-core@2.2.3/lib/reducers/stateId.js",
            "npm:dnd-core@2.2.3/lib/utils/getNextUniqueId.js",
            "npm:dnd-core@2.2.3/lib/utils/matchesType.js",
            "npm:fbjs@0.8.9/lib/CSSCore.js",
            "npm:fbjs@0.8.9/lib/EventListener.js",
            "npm:fbjs@0.8.9/lib/ExecutionEnvironment.js",
            "npm:fbjs@0.8.9/lib/camelize.js",
            "npm:fbjs@0.8.9/lib/camelizeStyleName.js",
            "npm:fbjs@0.8.9/lib/containsNode.js",
            "npm:fbjs@0.8.9/lib/createArrayFromMixed.js",
            "npm:fbjs@0.8.9/lib/createNodesFromMarkup.js",
            "npm:fbjs@0.8.9/lib/emptyFunction.js",
            "npm:fbjs@0.8.9/lib/emptyObject.js",
            "npm:fbjs@0.8.9/lib/focusNode.js",
            "npm:fbjs@0.8.9/lib/getActiveElement.js",
            "npm:fbjs@0.8.9/lib/getMarkupWrap.js",
            "npm:fbjs@0.8.9/lib/getUnboundedScrollPosition.js",
            "npm:fbjs@0.8.9/lib/hyphenate.js",
            "npm:fbjs@0.8.9/lib/hyphenateStyleName.js",
            "npm:fbjs@0.8.9/lib/invariant.js",
            "npm:fbjs@0.8.9/lib/isNode.js",
            "npm:fbjs@0.8.9/lib/isTextNode.js",
            "npm:fbjs@0.8.9/lib/memoizeStringOnly.js",
            "npm:fbjs@0.8.9/lib/performance.js",
            "npm:fbjs@0.8.9/lib/performanceNow.js",
            "npm:fbjs@0.8.9/lib/shallowEqual.js",
            "npm:fbjs@0.8.9/lib/warning.js",
            "npm:history@3.2.1/lib/Actions.js",
            "npm:history@3.2.1/lib/AsyncUtils.js",
            "npm:history@3.2.1/lib/BrowserProtocol.js",
            "npm:history@3.2.1/lib/DOMStateStorage.js",
            "npm:history@3.2.1/lib/DOMUtils.js",
            "npm:history@3.2.1/lib/ExecutionEnvironment.js",
            "npm:history@3.2.1/lib/HashProtocol.js",
            "npm:history@3.2.1/lib/LocationUtils.js",
            "npm:history@3.2.1/lib/PathUtils.js",
            "npm:history@3.2.1/lib/RefreshProtocol.js",
            "npm:history@3.2.1/lib/createBrowserHistory.js",
            "npm:history@3.2.1/lib/createHashHistory.js",
            "npm:history@3.2.1/lib/createHistory.js",
            "npm:history@3.2.1/lib/createMemoryHistory.js",
            "npm:history@3.2.1/lib/runTransitionHook.js",
            "npm:history@3.2.1/lib/useBasename.js",
            "npm:history@3.2.1/lib/useQueries.js",
            "npm:hoist-non-react-statics@1.2.0.js",
            "npm:hoist-non-react-statics@1.2.0/index.js",
            "npm:invariant@2.2.2.js",
            "npm:invariant@2.2.2/browser.js",
            "npm:lodash.isfunction@3.0.8.js",
            "npm:lodash.isfunction@3.0.8/index.js",
            "npm:lodash.isobject@3.0.2.js",
            "npm:lodash.isobject@3.0.2/index.js",
            "npm:lodash.omit@4.5.0.js",
            "npm:lodash.omit@4.5.0/index.js",
            "npm:lodash.tonumber@4.0.3.js",
            "npm:lodash.tonumber@4.0.3/index.js",
            "npm:lodash@4.17.4/_DataView.js",
            "npm:lodash@4.17.4/_Hash.js",
            "npm:lodash@4.17.4/_ListCache.js",
            "npm:lodash@4.17.4/_Map.js",
            "npm:lodash@4.17.4/_MapCache.js",
            "npm:lodash@4.17.4/_Promise.js",
            "npm:lodash@4.17.4/_Set.js",
            "npm:lodash@4.17.4/_SetCache.js",
            "npm:lodash@4.17.4/_Stack.js",
            "npm:lodash@4.17.4/_Symbol.js",
            "npm:lodash@4.17.4/_Uint8Array.js",
            "npm:lodash@4.17.4/_WeakMap.js",
            "npm:lodash@4.17.4/_addMapEntry.js",
            "npm:lodash@4.17.4/_addSetEntry.js",
            "npm:lodash@4.17.4/_apply.js",
            "npm:lodash@4.17.4/_arrayEach.js",
            "npm:lodash@4.17.4/_arrayFilter.js",
            "npm:lodash@4.17.4/_arrayIncludes.js",
            "npm:lodash@4.17.4/_arrayIncludesWith.js",
            "npm:lodash@4.17.4/_arrayLikeKeys.js",
            "npm:lodash@4.17.4/_arrayMap.js",
            "npm:lodash@4.17.4/_arrayPush.js",
            "npm:lodash@4.17.4/_arrayReduce.js",
            "npm:lodash@4.17.4/_arraySome.js",
            "npm:lodash@4.17.4/_assignValue.js",
            "npm:lodash@4.17.4/_assocIndexOf.js",
            "npm:lodash@4.17.4/_baseAssign.js",
            "npm:lodash@4.17.4/_baseAssignIn.js",
            "npm:lodash@4.17.4/_baseAssignValue.js",
            "npm:lodash@4.17.4/_baseClone.js",
            "npm:lodash@4.17.4/_baseCreate.js",
            "npm:lodash@4.17.4/_baseDifference.js",
            "npm:lodash@4.17.4/_baseEach.js",
            "npm:lodash@4.17.4/_baseFilter.js",
            "npm:lodash@4.17.4/_baseFindIndex.js",
            "npm:lodash@4.17.4/_baseFlatten.js",
            "npm:lodash@4.17.4/_baseFor.js",
            "npm:lodash@4.17.4/_baseForOwn.js",
            "npm:lodash@4.17.4/_baseGet.js",
            "npm:lodash@4.17.4/_baseGetAllKeys.js",
            "npm:lodash@4.17.4/_baseGetTag.js",
            "npm:lodash@4.17.4/_baseHasIn.js",
            "npm:lodash@4.17.4/_baseIndexOf.js",
            "npm:lodash@4.17.4/_baseIntersection.js",
            "npm:lodash@4.17.4/_baseIsArguments.js",
            "npm:lodash@4.17.4/_baseIsEqual.js",
            "npm:lodash@4.17.4/_baseIsEqualDeep.js",
            "npm:lodash@4.17.4/_baseIsMatch.js",
            "npm:lodash@4.17.4/_baseIsNaN.js",
            "npm:lodash@4.17.4/_baseIsNative.js",
            "npm:lodash@4.17.4/_baseIsTypedArray.js",
            "npm:lodash@4.17.4/_baseIteratee.js",
            "npm:lodash@4.17.4/_baseKeys.js",
            "npm:lodash@4.17.4/_baseKeysIn.js",
            "npm:lodash@4.17.4/_baseMatches.js",
            "npm:lodash@4.17.4/_baseMatchesProperty.js",
            "npm:lodash@4.17.4/_baseProperty.js",
            "npm:lodash@4.17.4/_basePropertyDeep.js",
            "npm:lodash@4.17.4/_baseRest.js",
            "npm:lodash@4.17.4/_baseSetToString.js",
            "npm:lodash@4.17.4/_baseSlice.js",
            "npm:lodash@4.17.4/_baseTimes.js",
            "npm:lodash@4.17.4/_baseToString.js",
            "npm:lodash@4.17.4/_baseUnary.js",
            "npm:lodash@4.17.4/_baseUniq.js",
            "npm:lodash@4.17.4/_baseUnset.js",
            "npm:lodash@4.17.4/_baseXor.js",
            "npm:lodash@4.17.4/_cacheHas.js",
            "npm:lodash@4.17.4/_castArrayLikeObject.js",
            "npm:lodash@4.17.4/_castPath.js",
            "npm:lodash@4.17.4/_cloneArrayBuffer.js",
            "npm:lodash@4.17.4/_cloneBuffer.js",
            "npm:lodash@4.17.4/_cloneDataView.js",
            "npm:lodash@4.17.4/_cloneMap.js",
            "npm:lodash@4.17.4/_cloneRegExp.js",
            "npm:lodash@4.17.4/_cloneSet.js",
            "npm:lodash@4.17.4/_cloneSymbol.js",
            "npm:lodash@4.17.4/_cloneTypedArray.js",
            "npm:lodash@4.17.4/_copyArray.js",
            "npm:lodash@4.17.4/_copyObject.js",
            "npm:lodash@4.17.4/_copySymbols.js",
            "npm:lodash@4.17.4/_copySymbolsIn.js",
            "npm:lodash@4.17.4/_coreJsData.js",
            "npm:lodash@4.17.4/_createAssigner.js",
            "npm:lodash@4.17.4/_createBaseEach.js",
            "npm:lodash@4.17.4/_createBaseFor.js",
            "npm:lodash@4.17.4/_createFind.js",
            "npm:lodash@4.17.4/_createSet.js",
            "npm:lodash@4.17.4/_customDefaultsAssignIn.js",
            "npm:lodash@4.17.4/_customOmitClone.js",
            "npm:lodash@4.17.4/_defineProperty.js",
            "npm:lodash@4.17.4/_equalArrays.js",
            "npm:lodash@4.17.4/_equalByTag.js",
            "npm:lodash@4.17.4/_equalObjects.js",
            "npm:lodash@4.17.4/_flatRest.js",
            "npm:lodash@4.17.4/_freeGlobal.js",
            "npm:lodash@4.17.4/_getAllKeys.js",
            "npm:lodash@4.17.4/_getAllKeysIn.js",
            "npm:lodash@4.17.4/_getMapData.js",
            "npm:lodash@4.17.4/_getMatchData.js",
            "npm:lodash@4.17.4/_getNative.js",
            "npm:lodash@4.17.4/_getPrototype.js",
            "npm:lodash@4.17.4/_getRawTag.js",
            "npm:lodash@4.17.4/_getSymbols.js",
            "npm:lodash@4.17.4/_getSymbolsIn.js",
            "npm:lodash@4.17.4/_getTag.js",
            "npm:lodash@4.17.4/_getValue.js",
            "npm:lodash@4.17.4/_hasPath.js",
            "npm:lodash@4.17.4/_hashClear.js",
            "npm:lodash@4.17.4/_hashDelete.js",
            "npm:lodash@4.17.4/_hashGet.js",
            "npm:lodash@4.17.4/_hashHas.js",
            "npm:lodash@4.17.4/_hashSet.js",
            "npm:lodash@4.17.4/_initCloneArray.js",
            "npm:lodash@4.17.4/_initCloneByTag.js",
            "npm:lodash@4.17.4/_initCloneObject.js",
            "npm:lodash@4.17.4/_isFlattenable.js",
            "npm:lodash@4.17.4/_isIndex.js",
            "npm:lodash@4.17.4/_isIterateeCall.js",
            "npm:lodash@4.17.4/_isKey.js",
            "npm:lodash@4.17.4/_isKeyable.js",
            "npm:lodash@4.17.4/_isMasked.js",
            "npm:lodash@4.17.4/_isPrototype.js",
            "npm:lodash@4.17.4/_isStrictComparable.js",
            "npm:lodash@4.17.4/_listCacheClear.js",
            "npm:lodash@4.17.4/_listCacheDelete.js",
            "npm:lodash@4.17.4/_listCacheGet.js",
            "npm:lodash@4.17.4/_listCacheHas.js",
            "npm:lodash@4.17.4/_listCacheSet.js",
            "npm:lodash@4.17.4/_mapCacheClear.js",
            "npm:lodash@4.17.4/_mapCacheDelete.js",
            "npm:lodash@4.17.4/_mapCacheGet.js",
            "npm:lodash@4.17.4/_mapCacheHas.js",
            "npm:lodash@4.17.4/_mapCacheSet.js",
            "npm:lodash@4.17.4/_mapToArray.js",
            "npm:lodash@4.17.4/_matchesStrictComparable.js",
            "npm:lodash@4.17.4/_memoizeCapped.js",
            "npm:lodash@4.17.4/_nativeCreate.js",
            "npm:lodash@4.17.4/_nativeKeys.js",
            "npm:lodash@4.17.4/_nativeKeysIn.js",
            "npm:lodash@4.17.4/_nodeUtil.js",
            "npm:lodash@4.17.4/_objectToString.js",
            "npm:lodash@4.17.4/_overArg.js",
            "npm:lodash@4.17.4/_overRest.js",
            "npm:lodash@4.17.4/_parent.js",
            "npm:lodash@4.17.4/_root.js",
            "npm:lodash@4.17.4/_setCacheAdd.js",
            "npm:lodash@4.17.4/_setCacheHas.js",
            "npm:lodash@4.17.4/_setToArray.js",
            "npm:lodash@4.17.4/_setToString.js",
            "npm:lodash@4.17.4/_shortOut.js",
            "npm:lodash@4.17.4/_stackClear.js",
            "npm:lodash@4.17.4/_stackDelete.js",
            "npm:lodash@4.17.4/_stackGet.js",
            "npm:lodash@4.17.4/_stackHas.js",
            "npm:lodash@4.17.4/_stackSet.js",
            "npm:lodash@4.17.4/_strictIndexOf.js",
            "npm:lodash@4.17.4/_stringToPath.js",
            "npm:lodash@4.17.4/_toKey.js",
            "npm:lodash@4.17.4/_toSource.js",
            "npm:lodash@4.17.4/assign.js",
            "npm:lodash@4.17.4/assignInWith.js",
            "npm:lodash@4.17.4/assignWith.js",
            "npm:lodash@4.17.4/concat.js",
            "npm:lodash@4.17.4/constant.js",
            "npm:lodash@4.17.4/defaults.js",
            "npm:lodash@4.17.4/eq.js",
            "npm:lodash@4.17.4/filter.js",
            "npm:lodash@4.17.4/find.js",
            "npm:lodash@4.17.4/findIndex.js",
            "npm:lodash@4.17.4/flatten.js",
            "npm:lodash@4.17.4/get.js",
            "npm:lodash@4.17.4/hasIn.js",
            "npm:lodash@4.17.4/identity.js",
            "npm:lodash@4.17.4/intersection.js",
            "npm:lodash@4.17.4/isArguments.js",
            "npm:lodash@4.17.4/isArray.js",
            "npm:lodash@4.17.4/isArrayLike.js",
            "npm:lodash@4.17.4/isArrayLikeObject.js",
            "npm:lodash@4.17.4/isBuffer.js",
            "npm:lodash@4.17.4/isEmpty.js",
            "npm:lodash@4.17.4/isFunction.js",
            "npm:lodash@4.17.4/isLength.js",
            "npm:lodash@4.17.4/isObject.js",
            "npm:lodash@4.17.4/isObjectLike.js",
            "npm:lodash@4.17.4/isPlainObject.js",
            "npm:lodash@4.17.4/isSymbol.js",
            "npm:lodash@4.17.4/isTypedArray.js",
            "npm:lodash@4.17.4/keys.js",
            "npm:lodash@4.17.4/keysIn.js",
            "npm:lodash@4.17.4/last.js",
            "npm:lodash@4.17.4/mapValues.js",
            "npm:lodash@4.17.4/memoize.js",
            "npm:lodash@4.17.4/noop.js",
            "npm:lodash@4.17.4/omit.js",
            "npm:lodash@4.17.4/property.js",
            "npm:lodash@4.17.4/stubArray.js",
            "npm:lodash@4.17.4/stubFalse.js",
            "npm:lodash@4.17.4/toFinite.js",
            "npm:lodash@4.17.4/toInteger.js",
            "npm:lodash@4.17.4/toNumber.js",
            "npm:lodash@4.17.4/toString.js",
            "npm:lodash@4.17.4/union.js",
            "npm:lodash@4.17.4/without.js",
            "npm:lodash@4.17.4/xor.js",
            "npm:moment@2.17.1.js",
            "npm:moment@2.17.1/locale/ru.js",
            "npm:moment@2.17.1/moment.js",
            "npm:object-assign@4.1.1.js",
            "npm:object-assign@4.1.1/index.js",
            "npm:process@0.11.9.js",
            "npm:process@0.11.9/browser.js",
            "npm:query-string@4.3.1.js",
            "npm:query-string@4.3.1/index.js",
            "npm:react-addons-css-transition-group@15.4.2.js",
            "npm:react-addons-css-transition-group@15.4.2/index.js",
            "npm:react-addons-transition-group@15.4.2.js",
            "npm:react-addons-transition-group@15.4.2/index.js",
            "npm:react-dnd-html5-backend@2.2.3.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/BrowserDetector.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/EnterLeaveCounter.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/HTML5Backend.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/MonotonicInterpolant.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/NativeDragSources.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/NativeTypes.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/OffsetUtils.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/getEmptyImage.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/index.js",
            "npm:react-dnd-html5-backend@2.2.3/lib/shallowEqual.js",
            "npm:react-dnd@2.2.3.js",
            "npm:react-dnd@2.2.3/lib/DragDropContext.js",
            "npm:react-dnd@2.2.3/lib/DragDropContextProvider.js",
            "npm:react-dnd@2.2.3/lib/DragLayer.js",
            "npm:react-dnd@2.2.3/lib/DragSource.js",
            "npm:react-dnd@2.2.3/lib/DropTarget.js",
            "npm:react-dnd@2.2.3/lib/areOptionsEqual.js",
            "npm:react-dnd@2.2.3/lib/createSourceConnector.js",
            "npm:react-dnd@2.2.3/lib/createSourceFactory.js",
            "npm:react-dnd@2.2.3/lib/createSourceMonitor.js",
            "npm:react-dnd@2.2.3/lib/createTargetConnector.js",
            "npm:react-dnd@2.2.3/lib/createTargetFactory.js",
            "npm:react-dnd@2.2.3/lib/createTargetMonitor.js",
            "npm:react-dnd@2.2.3/lib/decorateHandler.js",
            "npm:react-dnd@2.2.3/lib/index.js",
            "npm:react-dnd@2.2.3/lib/registerSource.js",
            "npm:react-dnd@2.2.3/lib/registerTarget.js",
            "npm:react-dnd@2.2.3/lib/utils/checkDecoratorArguments.js",
            "npm:react-dnd@2.2.3/lib/utils/cloneWithRef.js",
            "npm:react-dnd@2.2.3/lib/utils/isValidType.js",
            "npm:react-dnd@2.2.3/lib/utils/shallowEqual.js",
            "npm:react-dnd@2.2.3/lib/utils/shallowEqualScalar.js",
            "npm:react-dnd@2.2.3/lib/wrapConnectorHooks.js",
            "npm:react-dom@15.4.2.js",
            "npm:react-dom@15.4.2/index.js",
            "npm:react-dom@15.4.2/lib/ARIADOMPropertyConfig.js",
            "npm:react-dom@15.4.2/lib/AutoFocusUtils.js",
            "npm:react-dom@15.4.2/lib/BeforeInputEventPlugin.js",
            "npm:react-dom@15.4.2/lib/CSSProperty.js",
            "npm:react-dom@15.4.2/lib/CSSPropertyOperations.js",
            "npm:react-dom@15.4.2/lib/CallbackQueue.js",
            "npm:react-dom@15.4.2/lib/ChangeEventPlugin.js",
            "npm:react-dom@15.4.2/lib/DOMChildrenOperations.js",
            "npm:react-dom@15.4.2/lib/DOMLazyTree.js",
            "npm:react-dom@15.4.2/lib/DOMNamespaces.js",
            "npm:react-dom@15.4.2/lib/DOMProperty.js",
            "npm:react-dom@15.4.2/lib/DOMPropertyOperations.js",
            "npm:react-dom@15.4.2/lib/Danger.js",
            "npm:react-dom@15.4.2/lib/DefaultEventPluginOrder.js",
            "npm:react-dom@15.4.2/lib/EnterLeaveEventPlugin.js",
            "npm:react-dom@15.4.2/lib/EventConstants.js",
            "npm:react-dom@15.4.2/lib/EventPluginHub.js",
            "npm:react-dom@15.4.2/lib/EventPluginRegistry.js",
            "npm:react-dom@15.4.2/lib/EventPluginUtils.js",
            "npm:react-dom@15.4.2/lib/EventPropagators.js",
            "npm:react-dom@15.4.2/lib/FallbackCompositionState.js",
            "npm:react-dom@15.4.2/lib/HTMLDOMPropertyConfig.js",
            "npm:react-dom@15.4.2/lib/KeyEscapeUtils.js",
            "npm:react-dom@15.4.2/lib/LinkedValueUtils.js",
            "npm:react-dom@15.4.2/lib/PooledClass.js",
            "npm:react-dom@15.4.2/lib/ReactBrowserEventEmitter.js",
            "npm:react-dom@15.4.2/lib/ReactChildReconciler.js",
            "npm:react-dom@15.4.2/lib/ReactComponentBrowserEnvironment.js",
            "npm:react-dom@15.4.2/lib/ReactComponentEnvironment.js",
            "npm:react-dom@15.4.2/lib/ReactCompositeComponent.js",
            "npm:react-dom@15.4.2/lib/ReactDOM.js",
            "npm:react-dom@15.4.2/lib/ReactDOMComponent.js",
            "npm:react-dom@15.4.2/lib/ReactDOMComponentFlags.js",
            "npm:react-dom@15.4.2/lib/ReactDOMComponentTree.js",
            "npm:react-dom@15.4.2/lib/ReactDOMContainerInfo.js",
            "npm:react-dom@15.4.2/lib/ReactDOMEmptyComponent.js",
            "npm:react-dom@15.4.2/lib/ReactDOMFeatureFlags.js",
            "npm:react-dom@15.4.2/lib/ReactDOMIDOperations.js",
            "npm:react-dom@15.4.2/lib/ReactDOMInput.js",
            "npm:react-dom@15.4.2/lib/ReactDOMInvalidARIAHook.js",
            "npm:react-dom@15.4.2/lib/ReactDOMNullInputValuePropHook.js",
            "npm:react-dom@15.4.2/lib/ReactDOMOption.js",
            "npm:react-dom@15.4.2/lib/ReactDOMSelect.js",
            "npm:react-dom@15.4.2/lib/ReactDOMSelection.js",
            "npm:react-dom@15.4.2/lib/ReactDOMTextComponent.js",
            "npm:react-dom@15.4.2/lib/ReactDOMTextarea.js",
            "npm:react-dom@15.4.2/lib/ReactDOMTreeTraversal.js",
            "npm:react-dom@15.4.2/lib/ReactDOMUnknownPropertyHook.js",
            "npm:react-dom@15.4.2/lib/ReactDebugTool.js",
            "npm:react-dom@15.4.2/lib/ReactDefaultBatchingStrategy.js",
            "npm:react-dom@15.4.2/lib/ReactDefaultInjection.js",
            "npm:react-dom@15.4.2/lib/ReactElementSymbol.js",
            "npm:react-dom@15.4.2/lib/ReactEmptyComponent.js",
            "npm:react-dom@15.4.2/lib/ReactErrorUtils.js",
            "npm:react-dom@15.4.2/lib/ReactEventEmitterMixin.js",
            "npm:react-dom@15.4.2/lib/ReactEventListener.js",
            "npm:react-dom@15.4.2/lib/ReactFeatureFlags.js",
            "npm:react-dom@15.4.2/lib/ReactHostComponent.js",
            "npm:react-dom@15.4.2/lib/ReactHostOperationHistoryHook.js",
            "npm:react-dom@15.4.2/lib/ReactInjection.js",
            "npm:react-dom@15.4.2/lib/ReactInputSelection.js",
            "npm:react-dom@15.4.2/lib/ReactInstanceMap.js",
            "npm:react-dom@15.4.2/lib/ReactInstrumentation.js",
            "npm:react-dom@15.4.2/lib/ReactInvalidSetStateWarningHook.js",
            "npm:react-dom@15.4.2/lib/ReactMarkupChecksum.js",
            "npm:react-dom@15.4.2/lib/ReactMount.js",
            "npm:react-dom@15.4.2/lib/ReactMultiChild.js",
            "npm:react-dom@15.4.2/lib/ReactNodeTypes.js",
            "npm:react-dom@15.4.2/lib/ReactOwner.js",
            "npm:react-dom@15.4.2/lib/ReactPerf.js",
            "npm:react-dom@15.4.2/lib/ReactPropTypeLocationNames.js",
            "npm:react-dom@15.4.2/lib/ReactPropTypesSecret.js",
            "npm:react-dom@15.4.2/lib/ReactReconcileTransaction.js",
            "npm:react-dom@15.4.2/lib/ReactReconciler.js",
            "npm:react-dom@15.4.2/lib/ReactRef.js",
            "npm:react-dom@15.4.2/lib/ReactServerRenderingTransaction.js",
            "npm:react-dom@15.4.2/lib/ReactServerUpdateQueue.js",
            "npm:react-dom@15.4.2/lib/ReactShallowRenderer.js",
            "npm:react-dom@15.4.2/lib/ReactTestUtils.js",
            "npm:react-dom@15.4.2/lib/ReactUpdateQueue.js",
            "npm:react-dom@15.4.2/lib/ReactUpdates.js",
            "npm:react-dom@15.4.2/lib/ReactVersion.js",
            "npm:react-dom@15.4.2/lib/SVGDOMPropertyConfig.js",
            "npm:react-dom@15.4.2/lib/SelectEventPlugin.js",
            "npm:react-dom@15.4.2/lib/SimpleEventPlugin.js",
            "npm:react-dom@15.4.2/lib/SyntheticAnimationEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticClipboardEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticCompositionEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticDragEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticFocusEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticInputEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticKeyboardEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticMouseEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticTouchEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticTransitionEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticUIEvent.js",
            "npm:react-dom@15.4.2/lib/SyntheticWheelEvent.js",
            "npm:react-dom@15.4.2/lib/Transaction.js",
            "npm:react-dom@15.4.2/lib/ViewportMetrics.js",
            "npm:react-dom@15.4.2/lib/accumulateInto.js",
            "npm:react-dom@15.4.2/lib/adler32.js",
            "npm:react-dom@15.4.2/lib/checkReactTypeSpec.js",
            "npm:react-dom@15.4.2/lib/createMicrosoftUnsafeLocalFunction.js",
            "npm:react-dom@15.4.2/lib/dangerousStyleValue.js",
            "npm:react-dom@15.4.2/lib/escapeTextContentForBrowser.js",
            "npm:react-dom@15.4.2/lib/findDOMNode.js",
            "npm:react-dom@15.4.2/lib/flattenChildren.js",
            "npm:react-dom@15.4.2/lib/forEachAccumulated.js",
            "npm:react-dom@15.4.2/lib/getEventCharCode.js",
            "npm:react-dom@15.4.2/lib/getEventKey.js",
            "npm:react-dom@15.4.2/lib/getEventModifierState.js",
            "npm:react-dom@15.4.2/lib/getEventTarget.js",
            "npm:react-dom@15.4.2/lib/getHostComponentFromComposite.js",
            "npm:react-dom@15.4.2/lib/getIteratorFn.js",
            "npm:react-dom@15.4.2/lib/getNextDebugID.js",
            "npm:react-dom@15.4.2/lib/getNodeForCharacterOffset.js",
            "npm:react-dom@15.4.2/lib/getTextContentAccessor.js",
            "npm:react-dom@15.4.2/lib/getVendorPrefixedEventName.js",
            "npm:react-dom@15.4.2/lib/instantiateReactComponent.js",
            "npm:react-dom@15.4.2/lib/isEventSupported.js",
            "npm:react-dom@15.4.2/lib/isTextInputElement.js",
            "npm:react-dom@15.4.2/lib/quoteAttributeValueForBrowser.js",
            "npm:react-dom@15.4.2/lib/reactProdInvariant.js",
            "npm:react-dom@15.4.2/lib/renderSubtreeIntoContainer.js",
            "npm:react-dom@15.4.2/lib/setInnerHTML.js",
            "npm:react-dom@15.4.2/lib/setTextContent.js",
            "npm:react-dom@15.4.2/lib/shouldUpdateReactComponent.js",
            "npm:react-dom@15.4.2/lib/traverseAllChildren.js",
            "npm:react-dom@15.4.2/lib/validateDOMNesting.js",
            "npm:react-redux@5.0.2.js",
            "npm:react-redux@5.0.2/lib/components/Provider.js",
            "npm:react-redux@5.0.2/lib/components/connectAdvanced.js",
            "npm:react-redux@5.0.2/lib/connect/connect.js",
            "npm:react-redux@5.0.2/lib/connect/mapDispatchToProps.js",
            "npm:react-redux@5.0.2/lib/connect/mapStateToProps.js",
            "npm:react-redux@5.0.2/lib/connect/mergeProps.js",
            "npm:react-redux@5.0.2/lib/connect/selectorFactory.js",
            "npm:react-redux@5.0.2/lib/connect/verifySubselectors.js",
            "npm:react-redux@5.0.2/lib/connect/wrapMapToProps.js",
            "npm:react-redux@5.0.2/lib/index.js",
            "npm:react-redux@5.0.2/lib/utils/Subscription.js",
            "npm:react-redux@5.0.2/lib/utils/shallowEqual.js",
            "npm:react-redux@5.0.2/lib/utils/storeShape.js",
            "npm:react-redux@5.0.2/lib/utils/verifyPlainObject.js",
            "npm:react-redux@5.0.2/lib/utils/warning.js",
            "npm:react-router@3.0.2.js",
            "npm:react-router@3.0.2/lib/AsyncUtils.js",
            "npm:react-router@3.0.2/lib/ContextUtils.js",
            "npm:react-router@3.0.2/lib/IndexLink.js",
            "npm:react-router@3.0.2/lib/IndexRedirect.js",
            "npm:react-router@3.0.2/lib/IndexRoute.js",
            "npm:react-router@3.0.2/lib/InternalPropTypes.js",
            "npm:react-router@3.0.2/lib/Link.js",
            "npm:react-router@3.0.2/lib/PatternUtils.js",
            "npm:react-router@3.0.2/lib/PromiseUtils.js",
            "npm:react-router@3.0.2/lib/PropTypes.js",
            "npm:react-router@3.0.2/lib/Redirect.js",
            "npm:react-router@3.0.2/lib/Route.js",
            "npm:react-router@3.0.2/lib/RouteUtils.js",
            "npm:react-router@3.0.2/lib/Router.js",
            "npm:react-router@3.0.2/lib/RouterContext.js",
            "npm:react-router@3.0.2/lib/RouterUtils.js",
            "npm:react-router@3.0.2/lib/TransitionUtils.js",
            "npm:react-router@3.0.2/lib/applyRouterMiddleware.js",
            "npm:react-router@3.0.2/lib/browserHistory.js",
            "npm:react-router@3.0.2/lib/computeChangedRoutes.js",
            "npm:react-router@3.0.2/lib/createMemoryHistory.js",
            "npm:react-router@3.0.2/lib/createRouterHistory.js",
            "npm:react-router@3.0.2/lib/createTransitionManager.js",
            "npm:react-router@3.0.2/lib/getComponents.js",
            "npm:react-router@3.0.2/lib/getRouteParams.js",
            "npm:react-router@3.0.2/lib/hashHistory.js",
            "npm:react-router@3.0.2/lib/index.js",
            "npm:react-router@3.0.2/lib/isActive.js",
            "npm:react-router@3.0.2/lib/match.js",
            "npm:react-router@3.0.2/lib/matchRoutes.js",
            "npm:react-router@3.0.2/lib/routerWarning.js",
            "npm:react-router@3.0.2/lib/useRouterHistory.js",
            "npm:react-router@3.0.2/lib/withRouter.js",
            "npm:react@15.4.2.js",
            "npm:react@15.4.2/lib/KeyEscapeUtils.js",
            "npm:react@15.4.2/lib/PooledClass.js",
            "npm:react@15.4.2/lib/React.js",
            "npm:react@15.4.2/lib/ReactAddonsDOMDependencies.js",
            "npm:react@15.4.2/lib/ReactCSSTransitionGroup.js",
            "npm:react@15.4.2/lib/ReactCSSTransitionGroupChild.js",
            "npm:react@15.4.2/lib/ReactChildren.js",
            "npm:react@15.4.2/lib/ReactClass.js",
            "npm:react@15.4.2/lib/ReactComponent.js",
            "npm:react@15.4.2/lib/ReactComponentTreeHook.js",
            "npm:react@15.4.2/lib/ReactCurrentOwner.js",
            "npm:react@15.4.2/lib/ReactDOMFactories.js",
            "npm:react@15.4.2/lib/ReactElement.js",
            "npm:react@15.4.2/lib/ReactElementSymbol.js",
            "npm:react@15.4.2/lib/ReactElementValidator.js",
            "npm:react@15.4.2/lib/ReactNoopUpdateQueue.js",
            "npm:react@15.4.2/lib/ReactPropTypeLocationNames.js",
            "npm:react@15.4.2/lib/ReactPropTypes.js",
            "npm:react@15.4.2/lib/ReactPropTypesSecret.js",
            "npm:react@15.4.2/lib/ReactPureComponent.js",
            "npm:react@15.4.2/lib/ReactTransitionChildMapping.js",
            "npm:react@15.4.2/lib/ReactTransitionEvents.js",
            "npm:react@15.4.2/lib/ReactTransitionGroup.js",
            "npm:react@15.4.2/lib/ReactVersion.js",
            "npm:react@15.4.2/lib/canDefineProperty.js",
            "npm:react@15.4.2/lib/checkReactTypeSpec.js",
            "npm:react@15.4.2/lib/flattenChildren.js",
            "npm:react@15.4.2/lib/getIteratorFn.js",
            "npm:react@15.4.2/lib/onlyChild.js",
            "npm:react@15.4.2/lib/reactProdInvariant.js",
            "npm:react@15.4.2/lib/traverseAllChildren.js",
            "npm:react@15.4.2/react.js",
            "npm:reactstrap@4.1.0.js",
            "npm:reactstrap@4.1.0/lib/Alert.js",
            "npm:reactstrap@4.1.0/lib/Badge.js",
            "npm:reactstrap@4.1.0/lib/Breadcrumb.js",
            "npm:reactstrap@4.1.0/lib/BreadcrumbItem.js",
            "npm:reactstrap@4.1.0/lib/Button.js",
            "npm:reactstrap@4.1.0/lib/ButtonDropdown.js",
            "npm:reactstrap@4.1.0/lib/ButtonGroup.js",
            "npm:reactstrap@4.1.0/lib/ButtonToolbar.js",
            "npm:reactstrap@4.1.0/lib/Card.js",
            "npm:reactstrap@4.1.0/lib/CardBlock.js",
            "npm:reactstrap@4.1.0/lib/CardColumns.js",
            "npm:reactstrap@4.1.0/lib/CardDeck.js",
            "npm:reactstrap@4.1.0/lib/CardFooter.js",
            "npm:reactstrap@4.1.0/lib/CardGroup.js",
            "npm:reactstrap@4.1.0/lib/CardHeader.js",
            "npm:reactstrap@4.1.0/lib/CardImg.js",
            "npm:reactstrap@4.1.0/lib/CardImgOverlay.js",
            "npm:reactstrap@4.1.0/lib/CardLink.js",
            "npm:reactstrap@4.1.0/lib/CardSubtitle.js",
            "npm:reactstrap@4.1.0/lib/CardText.js",
            "npm:reactstrap@4.1.0/lib/CardTitle.js",
            "npm:reactstrap@4.1.0/lib/Col.js",
            "npm:reactstrap@4.1.0/lib/Collapse.js",
            "npm:reactstrap@4.1.0/lib/Container.js",
            "npm:reactstrap@4.1.0/lib/Dropdown.js",
            "npm:reactstrap@4.1.0/lib/DropdownItem.js",
            "npm:reactstrap@4.1.0/lib/DropdownMenu.js",
            "npm:reactstrap@4.1.0/lib/DropdownToggle.js",
            "npm:reactstrap@4.1.0/lib/Fade.js",
            "npm:reactstrap@4.1.0/lib/Form.js",
            "npm:reactstrap@4.1.0/lib/FormFeedback.js",
            "npm:reactstrap@4.1.0/lib/FormGroup.js",
            "npm:reactstrap@4.1.0/lib/FormText.js",
            "npm:reactstrap@4.1.0/lib/Input.js",
            "npm:reactstrap@4.1.0/lib/InputGroup.js",
            "npm:reactstrap@4.1.0/lib/InputGroupAddon.js",
            "npm:reactstrap@4.1.0/lib/InputGroupButton.js",
            "npm:reactstrap@4.1.0/lib/Jumbotron.js",
            "npm:reactstrap@4.1.0/lib/Label.js",
            "npm:reactstrap@4.1.0/lib/ListGroup.js",
            "npm:reactstrap@4.1.0/lib/ListGroupItem.js",
            "npm:reactstrap@4.1.0/lib/ListGroupItemHeading.js",
            "npm:reactstrap@4.1.0/lib/ListGroupItemText.js",
            "npm:reactstrap@4.1.0/lib/Media.js",
            "npm:reactstrap@4.1.0/lib/Modal.js",
            "npm:reactstrap@4.1.0/lib/ModalBody.js",
            "npm:reactstrap@4.1.0/lib/ModalFooter.js",
            "npm:reactstrap@4.1.0/lib/ModalHeader.js",
            "npm:reactstrap@4.1.0/lib/Nav.js",
            "npm:reactstrap@4.1.0/lib/NavDropdown.js",
            "npm:reactstrap@4.1.0/lib/NavItem.js",
            "npm:reactstrap@4.1.0/lib/NavLink.js",
            "npm:reactstrap@4.1.0/lib/Navbar.js",
            "npm:reactstrap@4.1.0/lib/NavbarBrand.js",
            "npm:reactstrap@4.1.0/lib/NavbarToggler.js",
            "npm:reactstrap@4.1.0/lib/Pagination.js",
            "npm:reactstrap@4.1.0/lib/PaginationItem.js",
            "npm:reactstrap@4.1.0/lib/PaginationLink.js",
            "npm:reactstrap@4.1.0/lib/Popover.js",
            "npm:reactstrap@4.1.0/lib/PopoverContent.js",
            "npm:reactstrap@4.1.0/lib/PopoverTitle.js",
            "npm:reactstrap@4.1.0/lib/Progress.js",
            "npm:reactstrap@4.1.0/lib/Row.js",
            "npm:reactstrap@4.1.0/lib/TabContent.js",
            "npm:reactstrap@4.1.0/lib/TabPane.js",
            "npm:reactstrap@4.1.0/lib/Table.js",
            "npm:reactstrap@4.1.0/lib/TetherContent.js",
            "npm:reactstrap@4.1.0/lib/Tooltip.js",
            "npm:reactstrap@4.1.0/lib/Uncontrolled.js",
            "npm:reactstrap@4.1.0/lib/index.js",
            "npm:reactstrap@4.1.0/lib/utils.js",
            "npm:redux@3.6.0.js",
            "npm:redux@3.6.0/lib/applyMiddleware.js",
            "npm:redux@3.6.0/lib/bindActionCreators.js",
            "npm:redux@3.6.0/lib/combineReducers.js",
            "npm:redux@3.6.0/lib/compose.js",
            "npm:redux@3.6.0/lib/createStore.js",
            "npm:redux@3.6.0/lib/index.js",
            "npm:redux@3.6.0/lib/utils/warning.js",
            "npm:strict-uri-encode@1.1.0.js",
            "npm:strict-uri-encode@1.1.0/index.js",
            "npm:symbol-observable@1.0.4.js",
            "npm:symbol-observable@1.0.4/index.js",
            "npm:symbol-observable@1.0.4/lib/index.js",
            "npm:symbol-observable@1.0.4/lib/ponyfill.js",
            "npm:tether@1.4.0.js",
            "npm:tether@1.4.0/dist/js/tether.js",
            "npm:warning@3.0.0.js",
            "npm:warning@3.0.0/browser.js",
            "reducers/common/cards.js",
            "reducers/common/user.js",
            "reducers/corporate_cards/cafeteria.js",
            "reducers/corporate_cards/card.js",
            "reducers/corporate_cards/manufacturing_facilities_inventory.js",
            "reducers/corporate_cards/manufacturing_facilities_inventory_issued.js",
            "reducers/corporate_cards/medical_center.js",
            "reducers/corporate_cards/medical_center_items.js",
            "reducers/corporate_cards/taskStatus.js",
            "reducers/corporate_cards/tasks.js",
            "reducers/corporate_cards/testing.js",
            "reducers/index.js",
            "reducers/loyalty/market.js",
            "reducers/social_tickets/cards.js",
            "reducers/social_tickets/categories.js",
            "reducers/social_tickets/events.js",
            "reducers/social_tickets/places.js",
            "reducers/transport/available_tickets.js",
            "reducers/transport/cards.js",
            "reducers/transport/log.js",
            "reducers/transport/ticket_free.js",
            "reducers/transport/tickets.js",
            "reducers/transport/transports_types.js",
            "routes.js",
            "store/configureStore.js",
            "utils/currencyFormat.js",
            "utils/dateFormat.js",
            "utils/index.js",
            "utils/normalizeDate.js",
            "utils/nsCreator.js",
            "utils/timeFormat.js",
            "vendor/gemini-scrollbar/index.js",
            "vendor/store/store.js"
        ]
    },
    "defaultJSExtensions": true,
    "map": {
        "babel": "npm:babel-core@5.8.38",
        "babel-runtime": "npm:babel-runtime@5.8.38",
        "classnames": "npm:classnames@2.2.5",
        "core-js": "npm:core-js@1.2.7",
        "gemini-scrollbar": "vendor/gemini-scrollbar/index",
        "github:jspm/nodelibs-assert@0.1.0": {
            "assert": "npm:assert@1.4.1"
        },
        "github:jspm/nodelibs-buffer@0.1.0": {
            "buffer": "npm:buffer@3.6.0"
        },
        "github:jspm/nodelibs-domain@0.1.0": {
            "domain-browser": "npm:domain-browser@1.1.7"
        },
        "github:jspm/nodelibs-events@0.1.1": {
            "events": "npm:events@1.0.2"
        },
        "github:jspm/nodelibs-http@1.7.1": {
            "Base64": "npm:Base64@0.2.1",
            "events": "github:jspm/nodelibs-events@0.1.1",
            "inherits": "npm:inherits@2.0.1",
            "stream": "github:jspm/nodelibs-stream@0.1.0",
            "url": "github:jspm/nodelibs-url@0.1.0",
            "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "github:jspm/nodelibs-https@0.1.0": {
            "https-browserify": "npm:https-browserify@0.0.0"
        },
        "github:jspm/nodelibs-path@0.1.0": {
            "path-browserify": "npm:path-browserify@0.0.0"
        },
        "github:jspm/nodelibs-process@0.1.2": {
            "process": "npm:process@0.11.9"
        },
        "github:jspm/nodelibs-stream@0.1.0": {
            "stream-browserify": "npm:stream-browserify@1.0.0"
        },
        "github:jspm/nodelibs-string_decoder@0.1.0": {
            "string_decoder": "npm:string_decoder@0.10.31"
        },
        "github:jspm/nodelibs-url@0.1.0": {
            "url": "npm:url@0.10.3"
        },
        "github:jspm/nodelibs-util@0.1.0": {
            "util": "npm:util@0.10.3"
        },
        "github:jspm/nodelibs-vm@0.1.0": {
            "vm-browserify": "npm:vm-browserify@0.0.4"
        },
        "github:jspm/nodelibs-zlib@0.1.0": {
            "browserify-zlib": "npm:browserify-zlib@0.1.4"
        },
        "jquery": "npm:jquery@3.1.1",
        "lodash": "npm:lodash@4.17.4",
        "lodash.assign": "npm:lodash.assign@4.2.0",
        "moment": "npm:moment@2.17.1",
        "npm:asap@2.0.5": {
            "domain": "github:jspm/nodelibs-domain@0.1.0",
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:assert@1.4.1": {
            "assert": "github:jspm/nodelibs-assert@0.1.0",
            "buffer": "github:jspm/nodelibs-buffer@0.1.0",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "util": "npm:util@0.10.3"
        },
        "npm:babel-runtime@5.8.38": {
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:browserify-zlib@0.1.4": {
            "assert": "github:jspm/nodelibs-assert@0.1.0",
            "buffer": "github:jspm/nodelibs-buffer@0.1.0",
            "pako": "npm:pako@0.2.9",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "readable-stream": "npm:readable-stream@2.2.2",
            "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:buffer-shims@1.0.0": {
            "buffer": "github:jspm/nodelibs-buffer@0.1.0"
        },
        "npm:buffer@3.6.0": {
            "base64-js": "npm:base64-js@0.0.8",
            "child_process": "github:jspm/nodelibs-child_process@0.1.0",
            "fs": "github:jspm/nodelibs-fs@0.1.2",
            "ieee754": "npm:ieee754@1.1.8",
            "isarray": "npm:isarray@1.0.0",
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:core-js@1.2.7": {
            "fs": "github:jspm/nodelibs-fs@0.1.2",
            "path": "github:jspm/nodelibs-path@0.1.0",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "systemjs-json": "github:systemjs/plugin-json@0.1.2"
        },
        "npm:core-util-is@1.0.2": {
            "buffer": "github:jspm/nodelibs-buffer@0.1.0"
        },
        "npm:dnd-core@2.2.3": {
            "asap": "npm:asap@2.0.5",
            "invariant": "npm:invariant@2.2.2",
            "lodash": "npm:lodash@4.17.4",
            "redux": "npm:redux@3.6.0"
        },
        "npm:domain-browser@1.1.7": {
            "events": "github:jspm/nodelibs-events@0.1.1"
        },
        "npm:encoding@0.1.12": {
            "buffer": "github:jspm/nodelibs-buffer@0.1.0",
            "iconv-lite": "npm:iconv-lite@0.4.15"
        },
        "npm:fbjs@0.8.9": {
            "core-js": "npm:core-js@1.2.7",
            "isomorphic-fetch": "npm:isomorphic-fetch@2.2.1",
            "loose-envify": "npm:loose-envify@1.3.1",
            "object-assign": "npm:object-assign@4.1.1",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "promise": "npm:promise@7.1.1",
            "setimmediate": "npm:setimmediate@1.0.5",
            "ua-parser-js": "npm:ua-parser-js@0.7.12"
        },
        "npm:history@3.2.1": {
            "invariant": "npm:invariant@2.2.2",
            "loose-envify": "npm:loose-envify@1.3.1",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "query-string": "npm:query-string@4.3.1",
            "warning": "npm:warning@3.0.0"
        },
        "npm:https-browserify@0.0.0": {
            "http": "github:jspm/nodelibs-http@1.7.1"
        },
        "npm:iconv-lite@0.4.15": {
            "buffer": "github:jspm/nodelibs-buffer@0.1.0",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "stream": "github:jspm/nodelibs-stream@0.1.0",
            "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0",
            "systemjs-json": "github:systemjs/plugin-json@0.1.2"
        },
        "npm:inherits@2.0.1": {
            "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:invariant@2.2.2": {
            "loose-envify": "npm:loose-envify@1.3.1",
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:isomorphic-fetch@2.2.1": {
            "node-fetch": "npm:node-fetch@1.6.3",
            "whatwg-fetch": "npm:whatwg-fetch@2.0.2"
        },
        "npm:lodash.omit@4.5.0": {
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:lodash.tonumber@4.0.3": {
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:loose-envify@1.3.1": {
            "fs": "github:jspm/nodelibs-fs@0.1.2",
            "js-tokens": "npm:js-tokens@3.0.1",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "stream": "github:jspm/nodelibs-stream@0.1.0",
            "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:node-fetch@1.6.3": {
            "buffer": "github:jspm/nodelibs-buffer@0.1.0",
            "encoding": "npm:encoding@0.1.12",
            "http": "github:jspm/nodelibs-http@1.7.1",
            "https": "github:jspm/nodelibs-https@0.1.0",
            "is-stream": "npm:is-stream@1.1.0",
            "stream": "github:jspm/nodelibs-stream@0.1.0",
            "url": "github:jspm/nodelibs-url@0.1.0",
            "util": "github:jspm/nodelibs-util@0.1.0",
            "zlib": "github:jspm/nodelibs-zlib@0.1.0"
        },
        "npm:pako@0.2.9": {
            "buffer": "github:jspm/nodelibs-buffer@0.1.0",
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:path-browserify@0.0.0": {
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:process-nextick-args@1.0.7": {
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:process@0.11.9": {
            "assert": "github:jspm/nodelibs-assert@0.1.0",
            "fs": "github:jspm/nodelibs-fs@0.1.2",
            "vm": "github:jspm/nodelibs-vm@0.1.0"
        },
        "npm:promise@7.1.1": {
            "asap": "npm:asap@2.0.5",
            "fs": "github:jspm/nodelibs-fs@0.1.2"
        },
        "npm:punycode@1.3.2": {
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:query-string@4.3.1": {
            "object-assign": "npm:object-assign@4.1.1",
            "strict-uri-encode": "npm:strict-uri-encode@1.1.0"
        },
        "npm:react-addons-css-transition-group@15.4.2": {
            "fbjs": "npm:fbjs@0.8.9",
            "object-assign": "npm:object-assign@4.1.1",
            "react": "npm:react@15.4.2"
        },
        "npm:react-addons-transition-group@15.4.2": {
            "fbjs": "npm:fbjs@0.8.9",
            "object-assign": "npm:object-assign@4.1.1",
            "react": "npm:react@15.4.2"
        },
        "npm:react-datetime@2.8.3": {
            "moment": "npm:moment@2.17.1",
            "object-assign": "npm:object-assign@3.0.0",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "react": "npm:react@15.4.2",
            "react-dom": "npm:react-dom@15.4.2",
            "react-onclickoutside": "npm:react-onclickoutside@4.9.0"
        },
        "npm:react-dnd-html5-backend@2.2.3": {
            "lodash": "npm:lodash@4.17.4",
            "react-dnd": "npm:react-dnd@2.2.3"
        },
        "npm:react-dnd@2.2.3": {
            "disposables": "npm:disposables@1.0.1",
            "dnd-core": "npm:dnd-core@2.2.3",
            "hoist-non-react-statics": "npm:hoist-non-react-statics@1.2.0",
            "invariant": "npm:invariant@2.2.2",
            "lodash": "npm:lodash@4.17.4",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "react": "npm:react@15.4.2"
        },
        "npm:react-dom@15.4.2": {
            "fbjs": "npm:fbjs@0.8.9",
            "loose-envify": "npm:loose-envify@1.3.1",
            "object-assign": "npm:object-assign@4.1.1",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "react": "npm:react@15.4.2"
        },
        "npm:react-onclickoutside@4.9.0": {
            "object-assign": "npm:object-assign@4.1.1",
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:react-redux@5.0.2": {
            "hoist-non-react-statics": "npm:hoist-non-react-statics@1.2.0",
            "invariant": "npm:invariant@2.2.2",
            "lodash": "npm:lodash@4.17.4",
            "lodash-es": "npm:lodash-es@4.17.4",
            "loose-envify": "npm:loose-envify@1.3.1",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "react": "npm:react@15.4.2",
            "redux": "npm:redux@3.6.0"
        },
        "npm:react-router@3.0.2": {
            "history": "npm:history@3.2.1",
            "hoist-non-react-statics": "npm:hoist-non-react-statics@1.2.0",
            "invariant": "npm:invariant@2.2.2",
            "loose-envify": "npm:loose-envify@1.3.1",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "react": "npm:react@15.4.2",
            "warning": "npm:warning@3.0.0"
        },
        "npm:react@15.4.2": {
            "fbjs": "npm:fbjs@0.8.9",
            "loose-envify": "npm:loose-envify@1.3.1",
            "object-assign": "npm:object-assign@4.1.1",
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:reactstrap@4.1.0": {
            "classnames": "npm:classnames@2.2.5",
            "lodash.isfunction": "npm:lodash.isfunction@3.0.8",
            "lodash.isobject": "npm:lodash.isobject@3.0.2",
            "lodash.omit": "npm:lodash.omit@4.5.0",
            "lodash.tonumber": "npm:lodash.tonumber@4.0.3",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "react": "npm:react@15.4.2",
            "react-addons-css-transition-group": "npm:react-addons-css-transition-group@15.4.2",
            "react-addons-transition-group": "npm:react-addons-transition-group@15.4.2",
            "react-dom": "npm:react-dom@15.4.2",
            "tether": "npm:tether@1.4.0"
        },
        "npm:readable-stream@1.1.14": {
            "buffer": "github:jspm/nodelibs-buffer@0.1.0",
            "core-util-is": "npm:core-util-is@1.0.2",
            "events": "github:jspm/nodelibs-events@0.1.1",
            "inherits": "npm:inherits@2.0.1",
            "isarray": "npm:isarray@0.0.1",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "stream-browserify": "npm:stream-browserify@1.0.0",
            "string_decoder": "npm:string_decoder@0.10.31"
        },
        "npm:readable-stream@2.2.2": {
            "buffer": "github:jspm/nodelibs-buffer@0.1.0",
            "buffer-shims": "npm:buffer-shims@1.0.0",
            "core-util-is": "npm:core-util-is@1.0.2",
            "events": "github:jspm/nodelibs-events@0.1.1",
            "inherits": "npm:inherits@2.0.1",
            "isarray": "npm:isarray@1.0.0",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "process-nextick-args": "npm:process-nextick-args@1.0.7",
            "string_decoder": "npm:string_decoder@0.10.31",
            "util-deprecate": "npm:util-deprecate@1.0.2"
        },
        "npm:redux@3.6.0": {
            "lodash": "npm:lodash@4.17.4",
            "lodash-es": "npm:lodash-es@4.17.4",
            "loose-envify": "npm:loose-envify@1.3.1",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "symbol-observable": "npm:symbol-observable@1.0.4"
        },
        "npm:setimmediate@1.0.5": {
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:stream-browserify@1.0.0": {
            "events": "github:jspm/nodelibs-events@0.1.1",
            "inherits": "npm:inherits@2.0.1",
            "readable-stream": "npm:readable-stream@1.1.14"
        },
        "npm:string_decoder@0.10.31": {
            "buffer": "github:jspm/nodelibs-buffer@0.1.0"
        },
        "npm:tether@1.4.0": {
            "process": "github:jspm/nodelibs-process@0.1.2",
            "systemjs-json": "github:systemjs/plugin-json@0.1.2"
        },
        "npm:ua-parser-js@0.7.12": {
            "systemjs-json": "github:systemjs/plugin-json@0.1.2"
        },
        "npm:url@0.10.3": {
            "assert": "github:jspm/nodelibs-assert@0.1.0",
            "punycode": "npm:punycode@1.3.2",
            "querystring": "npm:querystring@0.2.0",
            "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:util-deprecate@1.0.2": {
            "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:util@0.10.3": {
            "inherits": "npm:inherits@2.0.1",
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:vm-browserify@0.0.4": {
            "indexof": "npm:indexof@0.0.1"
        },
        "npm:warning@3.0.0": {
            "loose-envify": "npm:loose-envify@1.3.1",
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "react": "npm:react@15.4.2",
        "react-addons-css-transition-group": "npm:react-addons-css-transition-group@15.4.2",
        "react-addons-transition-group": "npm:react-addons-transition-group@15.4.2",
        "react-datetime": "npm:react-datetime@2.8.3",
        "react-dnd": "npm:react-dnd@2.2.3",
        "react-dnd-html5-backend": "npm:react-dnd-html5-backend@2.2.3",
        "react-dom": "npm:react-dom@15.4.2",
        "react-redux": "npm:react-redux@5.0.2",
        "react-router": "npm:react-router@3.0.2",
        "reactstrap": "npm:reactstrap@4.1.0",
        "redux": "npm:redux@3.6.0",
        "store": "vendor/store/store",
        "utils": "utils/index"
    },
    "paths": {
        "github:*": "jspm_packages/github/*",
        "npm:*": "jspm_packages/npm/*"
    },
    "transpiler": "babel"
});